### ISSUE TITLE
Taxonomy pointing to worng page

### ISSUE THREAD

**Issue by andjar** [OleVik/grav-theme-scholar#13]
Hi Ole,

Thanks for this nice theme! I noticed that the taxonomy in the top of the pages were pointing towards category=<category>, whereas I think they should be pointing towards category:<category>. I guess this can be fixed in the user/themes/scholar/templates/macros/metadata.html.twig? Or maybe I am mistaken?

**Comment by OleVik** [comment]
As of now it needs to point towards regular query-parameters, as the `:` syntax has not been implemented because it is non-standard.
