### ISSUE TITLE
Feature: List of backlinks

### ISSUE THREAD

**Issue by andjar** [OleVik/grav-theme-scholar#14]
Hi Ole,

Having a list of backlinks is a quite hot feature at the moment, as it allows you to see new connections between ideas and content, and it can be easily integrated into this theme as well (eg. http://ewy.no/blog/tiddlywiki, the modified code can be found here: http://ewy.no/blog/en-begynnelse-grav)

Maybe it's worth considering?

**Comment by OleVik** [comment]
Which plugin are you using for getting the backlinks, [Perlkonig's](https://github.com/Perlkonig/grav-plugin-backlinks)? Looking at the code, are backlinks all internal within the site? That is, are they then distinct from "pingbacks"? Both would be a useful feature, the former easier to integrate of course.

Scholar's architecture is very flexible and extensible, so adding in features in subservient plugins is quite a lot easier than with other plugins, so it may well be a viable extension.

**Comment by andjar** [comment]
Yeah, it is using Perlkonig's backlink plugin and list those linking to the current page. A [reddit search](https://www.google.com/search?q=backlinks+roam+research+site:www.reddit.com) shows that it is a popular feature request, especially for note taking applications. I agree with you that scholar semms very flexible and is structured in a very logical manner, well done!

**Comment by OleVik** [comment]
The most apt manner of integration would be to utilize Perlkonig's plugins, which I know to be excellently written, and use the data if the plugins are exposing it. There are some varied conventions for where to render backlinks and pingbacks, though I would favor below the related Page(s) links but above the footer. Eg. above "Made with the Scholar Theme, powered by Grav" on https://olevik.me/staging/grav-skeleton-scholar/blog/overcast.

In the Scholar theme this would just be a default for where to render the template, easily overridden by child-themes. I'll evaluate whether both warrant feature into the core set of templates, or whether it would be better to expose them as components.

**Comment by OleVik** [comment]
I added a component compatible with - and dependent on - the Backlinks-plugin, named "What Links Here" in [v2.1.0-beta.1](https://github.com/OleVik/grav-theme-scholar/releases/tag/2.1.0-beta.1). The term "backlinks" is a bit misleading, as it's also used more generally for external links to a page, essentially pingbacks and webmentions. "What Links Here" seems to be more common in the wiki-software from which it stems.

**Comment by andjar** [comment]
Very nice, Ole! Thank you, I am excited to test it!

**Comment by OleVik** [comment]
It's available on the GPM now if you have it set to `testing` rather than `stable`, and thanks for the suggestion and testing.

**Comment by OleVik** [comment]
Released as stable in [v2.1.0](https://github.com/OleVik/grav-theme-scholar/releases/tag/2.1.0).
