### ISSUE TITLE
Selecting a theme style crashes site

### ISSUE THREAD

**Issue by bleutzinn** [OleVik/grav-theme-scholar#23]
Trying different styles I selected "Berlin" instead of default in the theme configuration. Then I tried "Burgundy" and the site gave me a  Whoops: "Invalid argument supplied for foreach()" at line 426 in `scholar.php`. This error also prevents the use of Admin.

So I resorted to the CLI and reset the style in `user/config/themes/scholar.yaml` to `default` and cleared the Grav cache. Unfortunately the error persists.

I'm using Scholar theme v3.0.0 with Grav v1.7.15 and Admin v1.10.15 on Linux using Apache.

**Comment by OleVik** [comment]
Bah, humbug! That's a carry-over from Grav 1.6, I'll check it out as soon as I can.

**Comment by OleVik** [comment]
By the way, what's your server-environment? Specifically, what version of PHP are you running?

**Comment by OleVik** [comment]
This should be fixed in [3.0.1](https://github.com/OleVik/grav-theme-scholar/releases/tag/3.0.1), where there's a more graceful return from components not set in the configuration.
