### ISSUE TITLE
Documentation Navigation not present

### ISSUE THREAD

**Issue by guategeek** [OleVik/grav-theme-scholar#29]
I have been trying to set up a grav install where I can have documentation for multiple projects in one site. Your theme looked like it allowed this, where as the learn2 theme is just for documentation of one project per install of Grav.

To keep thing simple I decided to start with your skeleton.

1. Installed it on my shared hosting (dreamhost)
2. upgraded Grav to current (1.7.23) and updated all of the plugins to latest
3. Got the same error referenced [here](https://github.com/OleVik/grav-theme-scholar/issues/27) so I went into the theme and removed the "what-links-here" component from the list.
4. Now my site loads, great!
5. Go to the documentation section and there is no side navigation.

In fact, Documentation, Blog, CV and Book all don't show any content beyond the container page. For example (Note I deleted the image on the documentation page)
![image](https://user-images.githubusercontent.com/868801/137029393-e2ae317c-95de-4f6f-9290-20bbc535629d.png)

What template is the documentation page supposed to use? Why isn't the navigation showing up.

To reproduce simply grab the skeleton, and upgrade grav and the plugins, should have the same issue I have.

**Comment by Snck3rs** [comment]
I can confirm the "what_links_here" - problem. After a clean installation of the grav+admin-package and then switching to the scholar theme i get following error:

Template "partials/what_links_here.html.twig" is not defined in "default.html.twig" at line 43.

**Comment by OleVik** [comment]
This should be fixed by [v3.0.3](https://github.com/OleVik/grav-theme-scholar/releases/tag/3.0.3).

**Comment by malshar** [comment]
the same issue here with latest clean install of 
Grav v1.7.46
Admin v1.10.46
and scholar theme version 3.0.5 

menu is not present for Documentation, Blog, CV etc 
burger menu shows only on home page.
