### ISSUE TITLE
Unable to load the theme

### ISSUE THREAD

**Issue by ttben** [OleVik/grav-theme-scholar#3]
Hi!

We getting a fresh install of grav + admin, unzipping the content of this repo under `user/themes/scholar` ; the theme does not appear in the admin panel.

The grav logs contain 

```
[2020-02-12 19:12:45] grav.ERROR: Blueprint scholar/blueprints cannot be loaded: RecursiveDirectoryIterator::__construct(theme://css/styles): failed to open dir: &quot;\RocketTheme\Toolbox\StreamWrapper\ReadOnlyStream::dir_opendir&quot; call failed [] []
```

Do you have any idea?

Plus: the doc states that `./bin/gpm install scholar` should install the theme, but actually it returns `Nothing to install.`

**Comment by OleVik** [comment]
The Scholar theme has not yet been added to the GPM, but as you've noticed there's an open issue for it on the Core-repo from December 25th of 2019. It usually does not take this long to get it added, but hopefully soon. I'll look into the error.

**Comment by OleVik** [comment]
By the way, what version of Grav and possibly Admin are you running?

**Comment by ttben** [comment]
`Grav 1.6.20`
and `Admin v1.9.12`

Don't hesitate if you need me to test a whole fresh installation.

**Comment by OleVik** [comment]
Please try version [1.0.3](https://github.com/OleVik/grav-theme-scholar/releases/tag/1.0.3), it should gracefully skip blueprint-errors when Scholar is not the active theme.

**Comment by ttben** [comment]
The version `1.0.3` is working with grav `1.6.21` 😃👍
