### ISSUE TITLE
doumentation style

### ISSUE THREAD

**Issue by ufukayyildiz** [OleVik/grav-theme-scholar#31]
hi,

thanks for this theme.

i am try to set the theme like below documentation style but no success.

How can i do this?

Thank you.

**Comment by OleVik** [comment]
Which "below documentation style"?

**Comment by ufukayyildiz** [comment]
sorry for missed link.
https://olevik.me/staging/grav-skeleton-scholar/docs

and finally i set the theme as document style.

thanks.
