### ISSUE TITLE
what_links_here twig template missing

### ISSUE THREAD

**Issue by pmoreno-rodriguez** [OleVik/grav-theme-scholar#32]
HI.

By default the Scholar theme come with 'What-links-here' in Components. However, the '**what_links_here.html.twig**' file declarated in '**default.html.twig**' doesn't exist, and Grav show an error with the default template:

`Template "partials/what_links_here.html.twig" is not defined in "default.html.twig" at line 43.`

**Comment by OleVik** [comment]
It exists in the [components folder](https://github.com/OleVik/grav-theme-scholar/blob/master/components/what-links-here/partials/what_links_here.html.twig). Is that error thrown even with the [component registered](https://github.com/OleVik/grav-theme-scholar/blob/master/scholar.yaml#L22)?

**Comment by ckilb** [comment]
same here. did a fresh install of grav & scholar and i get this error message.

it's thrown _only_ with the component registered - as it's wrapped by an if condition. i guess the path to the template file is wrong.

**Comment by OleVik** [comment]
This should be fixed by [v3.0.3](https://github.com/OleVik/grav-theme-scholar/releases/tag/3.0.3).
