### ISSUE TITLE
Display RSS feed on Scholar homepage

### ISSUE THREAD

**Issue by cmadland** [OleVik/grav-theme-scholar#6]
Hi Ole,
Is it possible to display a feed from another grav site (http://grav.madland.ca/blog.rss) in the 'aside' area of the scholar homepage (scholar.madland.ca)?

**Comment by OleVik** [comment]
Sure it can, your child theme would just need to override parts of [index.html.twig](https://github.com/OleVik/grav-theme-scholar/blob/master/templates/index.html.twig#L13-L31), and render it there. You can even leverage the [listing.html.twig](https://github.com/OleVik/grav-theme-scholar/blob/master/templates/partials/page/listing.html.twig) template-partial for the rendering. Given the same structure, it will render like normal.
