### ISSUE TITLE
02.Documentation in admin GUI defaults to incorrect template

### ISSUE THREAD

**Issue by hellquist** [OleVik/grav-theme-scholar#9]
If I change something, anything, in the admin interface, for page 02.docs ("Documentation") and press save it will default to be saved as "article.md" as opposed to the original "docs.md", which has a completely different layout and functionality.

**Comment by OleVik** [comment]
That sounds like an upstream issue, I'll test and see if I can figure out why it happens.

**Comment by OleVik** [comment]
This should be fixed in [v1.0.4](https://github.com/OleVik/grav-theme-scholar/releases/tag/1.0.4).
